version: '3.7'

volumes:
    # mongo_data:
    sqlite_data:


services: 
    api:
        build: ./backend
        command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend:/backend
            - sqlite_data:/etc/db.db
        ports:
            - 8000:8000
    
    # mongo:
    #     image: mongo
    #     command: mongod --bind_ip 0.0.0.0
    #     restart: always
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: 'root'
    #         MONGO_INITDB_ROOT_PASSWORD: 'admin'
    #     volumes:
    #         - mongo_data:/data/db
    #     expose:
    #         - 27017
